name: cron

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call Vercel Deploy Hooks
        run: |
          curl --request POST \
          --url 'https://api.vercel.com/v1/integrations/deploy/${{ secrets.VERCEL_DEPLOY_HOOKS_SECRET }}?buildCache=false'